In [5]:
# 1. Conv2D 레이어 생성
# - filters=10: 10개의 필터(커널) 사용
# - kernel_size=(3, 3): 3x3 크기의 커널
import keras
from keras import layers

conv1 = layers.Conv2D(filters=10, kernel_size=(3, 3))
conv1

<Conv2D name=conv2d_1, built=False>

In [19]:
# 2. Conv2D 레이어 적용 테스트
# - 입력: (10, 28, 28, 1) → 10개 샘플, 28x28 이미지, 1채널(흑백)
# - 출력: (10, 26, 26, 10) → 3x3 커널로 convolution 후 크기가 줄어듦
import numpy as np

x = np.random.random((10, 28, 28, 1))  # 랜덤 데이터 생성
conv_out = conv1(x)  # Conv2D 레이어 적용

print(conv_out.shape)  # 출력 shape 확인

(10, 26, 26, 10)


In [7]:
# 3. Stride를 사용한 Conv2D
# - strides=(2,2): 커널을 2칸씩 이동하면서 convolution 수행
# - 출력 크기가 더 작아짐: (10, 13, 13, 10)
conv2 = layers.Conv2D(filters=10, kernel_size=(3, 3), strides=(2,2))

print(conv2(x).shape)

(10, 13, 13, 10)


In [9]:
# 4. Padding='same'과 stride를 함께 사용
# - padding='same': 입력과 출력의 크기 비율을 유지하도록 패딩 추가
# - stride=(2,2)로 인해 출력이 입력의 절반 크기: (10, 14, 14, 10)
conv3 = layers.Conv2D(filters=10, kernel_size=(3, 3), strides=(2, 2), padding='same')

print(conv3(x).shape)

(10, 14, 14, 10)


In [ ]:
# 5. Padding='same'만 사용 (기본 stride=1)
# - 입력과 출력의 크기가 동일하게 유지: (10, 28, 28, 10)
# - 특징 맵의 크기를 유지하면서 convolution 수행
conv4 = layers.Conv2D(filters=10, kernel_size=(3, 3), padding='same')

print(conv4(x).shape)


(10, 28, 28, 10)


In [13]:
# 6. AveragePooling2D 레이어 테스트
# - pool_size=2: 2x2 영역의 평균값으로 다운샘플링
# - pool_size=3: 3x3 영역의 평균값으로 다운샘플링
# - 공간 차원이 줄어들면서 계산량 감소 및 특징 추출
pool1 = layers.AveragePooling2D(pool_size=2)
pool2 = layers.AveragePooling2D(pool_size=3)

print(pool1(x).shape)  # (10, 14, 14, 1) - 절반 크기
print(pool2(x).shape)  # (10, 9, 9, 1) - 더 작은 크기

(10, 14, 14, 1)
(10, 9, 9, 1)


In [21]:
# 7. Dense(완전연결) 레이어 기본 사용
# - Dense(3): 3개의 출력 노드를 가진 완전연결 레이어
# - 입력 [5, 7]에 대해 랜덤 초기화된 가중치로 계산
dense1 = layers.Dense(3)

import numpy as np
x2 = np.array([[5, 7]])  # 2차원 입력 데이터

print(x2)  # 입력 확인
print(dense1(x2))  # 출력: (1, 3) 형태

[[5 7]]
tf.Tensor([[  1.860203  -10.448993   -2.4645417]], shape=(1, 3), dtype=float32)


In [17]:
# 8. Dense 레이어의 가중치 확인 및 수동 설정
# - get_weights(): 현재 가중치와 편향 확인
# - set_weights(): 가중치를 수동으로 설정
# - 가중치 행렬: (2, 3), 편향: (3,)
print(dense1.get_weights())  # 초기 랜덤 가중치 확인

dense1.set_weights([
    np.array([[1, 2, 3], [4, 5, 6]]),  # 가중치 행렬 설정
    np.array([0, 0, 0])  # 편향을 0으로 설정
])

print(dense1(x2))  # 새로운 가중치로 계산한 결과

[array([[ 0.65280044, -0.21822304, -0.310812  ],
       [ 0.474653  , -0.02614796, -0.33841002]], dtype=float32), array([0., 0., 0.], dtype=float32)]
tf.Tensor([[33. 45. 57.]], shape=(1, 3), dtype=float32)


In [18]:
# 9. Dense 레이어의 동작 원리 확인
# - Dense 레이어는 내부적으로 행렬 곱셈(np.dot)을 수행
# - 입력 x2와 가중치 행렬의 곱 = Dense 레이어의 출력
# - [5, 7] × [[1,2,3], [4,5,6]] = [33, 45, 57]
weight = dense1.get_weights()[0]  # 가중치 행렬 추출

print(np.dot(x2, weight))  # 수동 행렬 곱셈으로 동일한 결과 확인

[[33. 45. 57.]]
