In [1]:
# 반드시 첫 번째 셀에서 백엔드 설정
import os
os.environ['KERAS_BACKEND'] = 'torch'

# PyTorch MPS 확인
import torch
if torch.backends.mps.is_available():
    print("✅ MPS (Apple Silicon GPU) available")
else:
    print("❌ MPS not available, using CPU")

# Keras import (백엔드 확인)
import keras
print(f"🎯 Keras backend: {keras.backend.backend()}")

# TensorFlow는 import하지 않음!
import keras_hub

✅ MPS (Apple Silicon GPU) available
🎯 Keras backend: torch


In [2]:
from dotenv import load_dotenv
load_dotenv('../.env')


True

In [3]:
gpt2 = keras_hub.models.GPT2CausalLM.from_preset("gpt2_base_en")
gpt2.summary()

2025-08-19 20:09:32.082054: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4 Max
2025-08-19 20:09:32.082100: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 64.00 GB
2025-08-19 20:09:32.082106: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 24.00 GB
2025-08-19 20:09:32.082118: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-08-19 20:09:32.082136: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Preprocessor: "gpt2_causal_lm_preprocessor"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                                                  ┃                                   Config ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gpt2_tokenizer (GPT2Tokenizer)                                │                       Vocab size: 50,257 │
└───────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘

Model: "gpt2_causal_lm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ padding_mask (InputLayer)     │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_ids (InputLayer)        │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ gpt2_backbone (GPT2Backbone)  │ (None, None, 768)         │     124,439,808 │ padding_mask[0][0],        │
│                               │                           │                 │ token_ids[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_embedding               │ (None, None, 50257)       │      38,597,376 │ gpt2_backbone[0][0]        │
│ (ReversibleEmbedding)         │                           │                 │                            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 124,439,808 (474.70 MB)

 Trainable params: 124,439,808 (474.70 MB)

 Non-trainable params: 0 (0.00 B)

Preprocessor: "gpt2_causal_lm_preprocessor"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                                                  ┃                                   Config ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ gpt2_tokenizer (GPT2Tokenizer)                                │                       Vocab size: 50,257 │
└───────────────────────────────────────────────────────────────┴──────────────────────────────────────────┘

Model: "gpt2_causal_lm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ padding_mask (InputLayer)     │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_ids (InputLayer)        │ (None, None)              │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ gpt2_backbone (GPT2Backbone)  │ (None, None, 768)         │     124,439,808 │ padding_mask[0][0],        │
│                               │                           │                 │ token_ids[0][0]            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ token_embedding               │ (None, None, 50257)       │      38,597,376 │ gpt2_backbone[0][0]        │
│ (ReversibleEmbedding)         │                           │                 │                            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 124,439,808 (474.70 MB)

 Trainable params: 124,439,808 (474.70 MB)

 Non-trainable params: 0 (0.00 B)

In [4]:
text = gpt2.generate('stay hungry, stay', max_length=6)
print(text)

stay hungry, stay thirsty


In [5]:
text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay thirsty, stay tired of your own life.

You know what's


In [6]:
inputs, target, mask = gpt2.preprocessor('stay hungry, stay', sequence_length=10)

inputs, target, mask

({'token_ids': tensor([50256, 31712, 14720,    11,  2652, 50256,     0,     0,     0,     0],
         device='mps:0', dtype=torch.int32),
  'padding_mask': tensor([ True,  True,  True,  True,  True,  True, False, False, False, False],
         device='mps:0')},
 tensor([31712, 14720,    11,  2652, 50256,     0,     0,     0,     0,     0],
        device='mps:0', dtype=torch.int32),
 tensor([ True,  True,  True,  True,  True, False, False, False, False, False],
        device='mps:0'))

In [7]:
gpt2_tokenizer = gpt2.preprocessor.tokenizer

for ids in target:
    print(gpt2_tokenizer.id_to_token(ids), end=' ')

stay Ġhungry , Ġstay <|endoftext|> ! ! ! ! ! 

In [8]:
inputs = gpt2.preprocessor.generate_preprocess(['stay hungry, stay'], sequence_length=10)

inputs

{'token_ids': tensor([[50256, 31712, 14720,    11,  2652,     0,     0,     0,     0,     0]],
        device='mps:0', dtype=torch.int32),
 'padding_mask': tensor([[ True,  True,  True,  True,  True, False, False, False, False, False]],
        device='mps:0')}

In [9]:
outputs = gpt2.generate_function(inputs)

outputs

{'token_ids': tensor([[50256, 31712, 14720,    11,  2652,  5448,    13,   198,   198,  1135]],
        device='mps:0', dtype=torch.int32),
 'padding_mask': tensor([[True, True, True, True, True, True, True, True, True, True]],
        device='mps:0')}

In [10]:
gpt2.preprocessor.generate_postprocess(outputs)

['stay hungry, stay healthy.\n\nWe']

In [11]:
sampler = keras_hub.samplers.TopKSampler(k=10, temperature=0.5, seed=42)

gpt2.compile(sampler=sampler)

gpt2.generate('stay hungry, stay', max_length=20)

'stay hungry, stay warm, stay warm\n\nstay in your comfort zone and stay in the'

In [12]:
sampler = keras_hub.samplers.TopKSampler(k=10, temperature=5, seed=42)

gpt2.compile(sampler=sampler)

gpt2.generate('stay hungry, stay', max_length=20)

'stay hungry, stay warm -\n"The last three years has been a roller-skier'

In [13]:
import tensorflow as tf

gpt2.generate(tf.constant('stay hungry, stay'), max_length=20)

'stay hungry, stay thirsty: The first few years of a new era are filled by foodies'

In [14]:
sampler = keras_hub.samplers.TopPSampler(p=0.8, seed=42)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

text

'stay hungry, stay warm\n\ncoffee : ice cold not iced coffee\n\nch'

In [15]:
sampler = keras_hub.samplers.TopPSampler(p=0.8, k=1000, temperature=5, seed=42)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

text

'stay hungry, stay warm". Of myself rather: An that sounds . Aw many beeth whales'

In [16]:
gpt2.compile(sampler='top_p')

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay


In [17]:
gpt2.compile(sampler='greedy')

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay


In [18]:
import keras_hub

sampler = keras_hub.samplers.RandomSampler(temperature=5, seed=42)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay jacket Well Feesal negativeHub█ registered Fingeronel lazyRecord six athleticism Carly


In [19]:
import keras_hub

sampler = keras_hub.samplers.BeamSampler(num_beams=10, temperature=5)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay hydrated stay hydrated

Stay hydrated stay hydrated




In [20]:
import keras_hub

sampler = keras_hub.samplers.ContrastiveSampler(k=10, alpha=0.2)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay


In [21]:
import keras_hub

sampler = keras_hub.samplers.ContrastiveSampler(k=10, alpha=0.8)

gpt2.compile(sampler=sampler)

text = gpt2.generate('stay hungry, stay', max_length=20)

print(text)

stay hungry, stay thirsty


A lot has changed in the last 20 years. There are


In [22]:
from transformers import pipeline, set_seed

set_seed(42)

hf_gpt1 = pipeline('text-generation', model='openai-community/openai-gpt')

hf_gpt1('stay hungry, stay', max_length=20, truncation=True)

Device set to use mps:0


[{'generated_text': "stay hungry, stay dry. sometimes the temperature drops even farther down into a freezing winter and it's"}]

In [23]:
from transformers import pipeline, set_seed

set_seed(42)

hf_gpt1('stay hungry, stay', max_length=20, truncation=True, num_return_sequences=3)

[{'generated_text': "stay hungry, stay dry. sometimes the temperature drops even farther down into a freezing winter and it's"},
 {'generated_text': "stay hungry, stay out of my way and keep it in. if i were you, i 'd"},
 {'generated_text': 'stay hungry, stay out of trouble, get some more food in your bellies, and maybe some real'}]

In [24]:
from transformers import AutoTokenizer, AutoModelForCausalLM

hf_gpt2_tokenizer = AutoTokenizer.from_pretrained('gpt2')
hf_gpt2_model = AutoModelForCausalLM.from_pretrained('gpt2')

prep_data = hf_gpt2_tokenizer('stay hungry, stay', return_tensors='pt')
prep_data

{'input_ids': tensor([[31712, 14720,    11,  2652]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [25]:
set_seed(42)

hf_gpt2_model.generation_config.pad_token_id = hf_gpt2_model.generation_config.eos_token_id

prep_data = hf_gpt2_tokenizer('stay hungry, stay', return_tensors='pt')

outputs = hf_gpt2_model.generate(**prep_data, max_length=20)

print(outputs)

tensor([[31712, 14720,    11,  2652, 47124,    11,  2652, 47124,    11,  2652,
         47124,    11,  2652, 47124,    11,  2652, 47124,    11,  2652, 47124]])


In [26]:
hf_gpt2_tokenizer.batch_decode(outputs)

['stay hungry, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay thirsty, stay thirsty']

In [27]:
set_seed(42)

outputs = hf_gpt2_model.generate(**prep_data, max_length=20, do_sample=True)

hf_gpt2_tokenizer.batch_decode(outputs)

['stay hungry, stay thirsty and stay a little drunk in hot spots, stay in the kitchen and then']

In [28]:
set_seed(42)

outputs = hf_gpt2_model.generate(**prep_data, max_length=20, do_sample=True, top_p=0.8, temperature=5.0)

hf_gpt2_tokenizer.batch_decode(outputs)

['stay hungry, stay with mom," a female reporter in Toronto tells him . And to see something from']

In [29]:
set_seed(42)

outputs = hf_gpt2_model.generate(**prep_data, max_length=20, num_beams=5)

text = hf_gpt2_tokenizer.batch_decode(outputs)

print(text)

['stay hungry, stay hungry, stay hungry, stay hungry, stay hungry, stay hungry, stay hungry']


In [30]:
set_seed(42)

outputs = hf_gpt2_model.generate(**prep_data, max_length=20, num_beams=5, top_k=20, do_sample=True, temperature=5.0)

text = hf_gpt2_tokenizer.batch_decode(outputs)

print(text)

['stay hungry, stay in shape or get some rest for your kids. Your family will know you have']


In [31]:
set_seed(42)

outputs = hf_gpt2_model.generate(**prep_data, max_length=20, penalty_alpha=0.8)

text = hf_gpt2_tokenizer.batch_decode(outputs)

print(text)

["stay hungry, stay out of trouble\n\n\nDon't want us to be able to do that?"]


In [32]:
from transformers import GenerationConfig

GenerationConfig().to_dict()

{'max_length': 20,
 'max_new_tokens': None,
 'min_length': 0,
 'min_new_tokens': None,
 'early_stopping': False,
 'max_time': None,
 'stop_strings': None,
 'do_sample': False,
 'num_beams': 1,
 'num_beam_groups': 1,
 'penalty_alpha': None,
 'dola_layers': None,
 'use_cache': True,
 'cache_implementation': None,
 'cache_config': None,
 'return_legacy_cache': None,
 'temperature': 1.0,
 'top_k': 50,
 'top_p': 1.0,
 'min_p': None,
 'typical_p': 1.0,
 'epsilon_cutoff': 0.0,
 'eta_cutoff': 0.0,
 'diversity_penalty': 0.0,
 'repetition_penalty': 1.0,
 'encoder_repetition_penalty': 1.0,
 'length_penalty': 1.0,
 'no_repeat_ngram_size': 0,
 'bad_words_ids': None,
 'force_words_ids': None,
 'renormalize_logits': False,
 'constraints': None,
 'forced_bos_token_id': None,
 'forced_eos_token_id': None,
 'remove_invalid_values': False,
 'exponential_decay_length_penalty': None,
 'suppress_tokens': None,
 'begin_suppress_tokens': None,
 'forced_decoder_ids': None,
 'sequence_bias': None,
 'token_heali